// GENERATED by nice-generate-exports — do not edit by hand
// To update: edit package.exports.json and run `npm run generate-exports`

/** Semantic typography component for nice-react with full token support. */

export { default } from "./components/Typography"
export * from "./components/Typography"
export { TypographyStyles, getTypographyToken } from "./tokens"
