// GENERATED by nice-generate-exports — do not edit by hand
// To update: edit package.exports.json and run `npm run generate-exports`

/** Semantic ink component for nice-react with full token support. */

export { default } from "./components/Ink"
export * from "./components/Ink"
export { getInkToken } from "./tokens"
